on:
  push:

jobs:
  build-test-deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: |
          IMAGE="ghcr.io/dwdab/mycalc:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

  foo:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
