on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: |
          IMGAGE="ghcr.io/dwdab/mycalc:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
